Update to Julia v1.6
JuliaPhysics/SolidStateDetectors.jl pull request #135
Opened 2021-02-07 16:28 UTC by lmh91

PR to prepare for Julia v1.6. 
Do not merge till v1.6 is released.

2021-02-07 18:04 UTC, oschulz requested changes

2021-02-07 18:04 UTC, oschulz commented on .github/workflows/ci.yml
> +          - '1.6'
We should set this to '1', that will automatically use the latest Julia release.

2021-02-07 18:04 UTC, oschulz commented on .github/workflows/ci.yml
> +          version: '1.6'
We should set this to '1', that will automatically use the latest Julia release.

2021-02-07 18:37 UTC, oschulz commented
Nice - like this, we don't have to wait for the v1.6 release to merge it.

2021-02-07 18:39 UTC, lmh91 commented
That's true. 

Should we actually drop v1.0 already @oschulz?
v1.6 should become the next LTS version, right? 
Or do we wait till v1.7?

2021-02-07 19:13 UTC, oschulz commented
Let's set Julia v1.3 as the minimum right now (and also test on v1.3), many package have done that. If v1.6 seems likely to become the new LTS, but this will only be confirmed during the v1.7 release process, from what I understand.

2021-02-12 14:26 UTC, lmh91 commented
Okay, than I will leave v1.0 inside for now.

2021-02-12 14:26 UTC, merged