Add convenient constructor for `Ellipse`
JuliaPhysics/SolidStateDetectors.jl pull request #301
Opened 2022-06-14 07:40 UTC by SebastianRuffert

2022-06-14 07:45 UTC, fhagemann reviewed
Can you provide plots of (rotated and translated) `SurfacePrimitives` that you adapted in this PR to see that all `Ellipses` are defined the right way?

2022-06-15 07:25 UTC, fhagemann requested changes
The tests fail because the `lines` method for `TorusMantle` was not adapted.

Please adapt it (`src/ConstructiveSolidGeometry/SurfacePrimitives/TorusMantle.jl#L152`)

2022-06-15 09:02 UTC, SebastianRuffert commented on src/ConstructiveSolidGeometry/LinePrimitives/Ellipse.jl
>  #     * ...
Doc string says no, but struct says yes. Especially since we defined PartialCircle, phi should be allowed to be a real too

2022-06-15 14:25 UTC, fhagemann approved these changes

2022-06-15 14:26 UTC, merged