Improve depletion estimation
JuliaPhysics/SolidStateDetectors.jl pull request #430
Opened 2024-11-07 01:07 UTC by apmypb

2024-11-07 03:47 UTC, fhagemann commented on src/Simulation/DepletionVoltage.jl
> +    U = U > 0 ? min(U, U2) : min(U, U2)
Is this correct? Seems like one of them should be max instead of min (?)

2024-11-09 12:11 UTC, fhagemann commented
@zpdg could you please check if this resolves your issue?

2024-11-12 03:00 UTC, zpdg commented
> @zpdg could you please check if this resolves your issue?

Of course. This works well after the first "min" was changed to "max" in the `U = U > 0 ? min(U, U2) : min(U, U2)`. And the result is consistent with my code which simply rewrote MJD_siggen's code in julia.
My code: 
```julia
Umin=maximum(broadcast(c -> c.potential, sim.detector.contacts))
Umax=maximum(broadcast(c -> c.potential, sim.detector.contacts))
contact_id=determine_bias_voltage_contact_id(sim.detector)
tolerance=0.1

simDV = deepcopy(sim)
_adapt_weighting_potential_to_electric_potential_grid!(simDV, contact_id)
grid=simDV.electric_potential.grid
ϕT = simDV.electric_potential.data
ϕV = simDV.weighting_potentials[contact_id].data   

bias=simDV.detector.contacts[contact_id].potential
ϕρ=ϕT .-  (bias .* ϕV) # contribution from purities

inside = findall(simDV.point_types .& 4 .> 0)
U::T = 0

while Umax-Umin>tolerance
    U = (Umax + Umin)/2    
    judge=ϕρ[inside] .+ T(U) .* ϕV[inside]
    maximum(judge) - minimum(judge) < abs(U) ? Umax = U : Umin = U
end

dz=[1,-1,0,0]
dr=[0,0,1,-1]

grid_r=grid[1]
grid_z=grid[3]

U2_distance=Umax
for zi in 2:size(ϕT,3)-1
    for ri in 1:size(ϕT,1)-1
        if CartesianIndex(ri,1,zi) in inside
            test_v=-1

            for i in 1:4
                if (ri==1) && (i==3) # don't check the field along the r direction when r==0 mm
                    break
                end

                dV=ϕT[ri+dr[i],1,zi+dz[i]]-ϕT[ri,1,zi]
                dW=ϕV[ri+dr[i],1,zi+dz[i]]-ϕV[ri,1,zi]
                if (dW<0) && (dV<0) && (test_v<dV/dW)
                    test_v=dV/dW
                end
            end

            if (test_v>0) && (U2_distance>test_v)
                U2_distance=test_v
                vminr=ri
                vminz=zi
            end

        end
    end
end
U2=bias-U2_distance
U=max(U,U2)
```

2024-11-13 19:31 UTC, fhagemann requested changes

2024-11-13 19:31 UTC, fhagemann commented on test/depletion_test.jl
> +    @test undepleted && depleted
This test will not test the case we are trying to test. We want to add `depletion_handling` here:
```julia
    sim.detector = SolidStateDetector(sim.detector, contact_id=1, contact_potential=U₊)
    calculate_electric_potential!(sim, refinement_limits=0.01, depletion_handling = true)
    undepleted = !is_depleted(sim.point_types)
    sim.detector = SolidStateDetector(sim.detector, contact_id=1, contact_potential=U₋)
    calculate_electric_potential!(sim, refinement_limits=0.01, depletion_handling = true)
    depleted = is_depleted(sim.point_types)
    @test undepleted && depleted
```

2024-11-13 19:31 UTC, fhagemann commented on test/depletion_test.jl
> +    SolidStateDetectors._adapt_weighting_potential_to_electric_potential_grid!(sim, id)
Is this actually needed in the tests or is it done automatically in `estimate_depletion_voltage` anyhow?

2024-11-14 10:43 UTC, fhagemann commented on test/depletion_test.jl
>      undepleted = is_depleted(sim.point_types)
This is still missing an exclamation mark here.
We expect it to be undepleted, so this line should be: !is_depleted

2024-11-14 10:48 UTC, fhagemann commented on test/depletion_test.jl
> +        depletion_handling=true)
The depletion_handling = true needs to be passed to calculate_electric_potential!, not the SolidStateDetector

2024-11-15 13:25 UTC, fhagemann commented
Thanks! @apmypb

2024-11-15 13:53 UTC, fhagemann commented
I pushed once change that I wanted to incorporate for a long time.
And I renamed the test file to the test naming scheme `test_XXXX.jl`

2024-11-15 13:54 UTC, fhagemann approved these changes

2024-11-15 15:13 UTC, merged

2024-11-15 15:20 UTC, fhagemann commented
This will be released soon: https://github.com/JuliaRegistries/General/pull/119509